
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Feb 23 02:43:53 EST 2012
//----------------------------------------------------

package com.pascal.compiler.sr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int CHAR = 40;
  public static final int SEMI = 22;
  public static final int INT = 38;
  public static final int UNY_PLUS = 20;
  public static final int ARRAY = 3;
  public static final int LESS = 30;
  public static final int MINUS = 18;
  public static final int NOT = 8;
  public static final int AND = 2;
  public static final int TYPE = 14;
  public static final int OR = 10;
  public static final int COMMA = 23;
  public static final int BEGIN = 4;
  public static final int PLUS = 17;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int OF = 9;
  public static final int EOF = 0;
  public static final int GTR = 29;
  public static final int error = 1;
  public static final int PROGRAM = 11;
  public static final int LEFT_BRKT = 26;
  public static final int IDENT = 37;
  public static final int RT_PAREN = 25;
  public static final int ASSMNT = 35;
  public static final int EQ = 28;
  public static final int REAL = 39;
  public static final int TIMES = 16;
  public static final int COLON = 34;
  public static final int ELSE = 5;
  public static final int NOT_EQ = 33;
  public static final int LESS_EQ = 31;
  public static final int UNY_MINUS = 21;
  public static final int RT_BRKT = 27;
  public static final int THEN = 13;
  public static final int END = 6;
  public static final int LEFT_PAREN = 24;
  public static final int GTR_EQ = 32;
  public static final int VAR = 15;
  public static final int PROCEDURE = 12;
}

